FROM alpine:3.9.2

RUN apk add --update --no-cache \
    tzdata \
    gcc \
    python-dev \
    py-setuptools \
    musl-dev \
    libffi-dev \
    openssl-dev \
    libxml2-dev \
    libxslt-dev \
    jpeg-dev \
    zlib-dev \
    freetype-dev \
    lcms2-dev \
    openjpeg-dev \
    tiff-dev \
    tk-dev \
    tcl-dev \
    harfbuzz-dev \
    fribidi-dev \
    python2 \
    bash \
    py-mysqldb \
    supervisor && \
    python2 -m ensurepip
    rm -r /usr/lib/python*/ensurepip && \
    pip2 install --upgrade pip setuptools==44.0.0 && \


RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.11/main" >> /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.11/community" >> /etc/apk/repositories

RUN apk add --no-cache alpine-sdk swig

RUN apk add --no-cache zbar

RUN rm -r /root/.cache
